package dao;

import adt.HashTableInterface;
import entity.BillingRecord;
import entity.Guest;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import utility.DataFileLocator;

/**
 * BillingRecordDao.java - reads data/billing_records.txt, builds
 * BillingRecord objects, and attaches them to their Guest in guestTable.
 *
 * Notes:
 * - Only reads the file, builds objects, and stores them in the container -
 *   no business logic here.
 * - Must run after GuestDao, relying on
 *   guestTable.getEntry(new Guest(confirmationNumber)) to find the existing
 *   Guest.
 * - txt format: confirmationNumber,roomFee,extraCharges,totalAmount,
 *   pointsEarned,date (no billingId - that is generated by this DAO's own
 *   counter, the same way real checkout billing does it).
 * - billingId has prefix SBR, so it won't collide with BR IDs generated by
 *   manual checkout.
 *
 * @author All
 */
public class BillingRecordDao {

    private static final String FILE_PATH = "data/billing_records.txt";

    private int billingCounter = 0;

    public void loadBillingRecords(HashTableInterface<Guest> guestTable) {
        File file = DataFileLocator.locate(BillingRecordDao.class, FILE_PATH);
        if (file == null) {
            System.out.println("Failed to load " + FILE_PATH + ": file not found near project root");
            return;
        }
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty()) {
                    continue;
                }
                String[] fields = line.split(",");
                String confirmationNumber = fields[0].trim();
                double roomFee = Double.parseDouble(fields[1].trim());
                double extraCharges = Double.parseDouble(fields[2].trim());
                double totalAmount = Double.parseDouble(fields[3].trim());
                int pointsEarned = Integer.parseInt(fields[4].trim());
                String date = fields[5].trim();

                Guest guest = guestTable.getEntry(new Guest(confirmationNumber));
                if (guest == null) {
                    System.out.println("Skipped " + FILE_PATH + " row: no guest found for confirmation number " + confirmationNumber);
                    continue;
                }

                billingCounter++;
                String billingId = "SBR" + String.format("%06d", billingCounter);
                guest.addBillingRecord(new BillingRecord(billingId, confirmationNumber,
                        roomFee, extraCharges, totalAmount, pointsEarned, date));
            }
        } catch (IOException e) {
            System.out.println("Failed to load " + FILE_PATH + ": " + e.getMessage());
        }
    }
}
