package dao;

import adt.ListInterface;
import entity.Member;
import entity.PointsLedgerEntry;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Iterator;
import utility.DataFileLocator;

/**
 * PointsLedgerDao.java - reads data/points_ledger.txt, builds
 * PointsLedgerEntry objects, and adds them to the matching member's points
 * ledger list in memberList.
 *
 * Notes:
 * - Only reads the file, builds objects, and stores them in the container -
 *   no business logic here.
 * - Must run after MemberDao, using a linear search over memberList to find
 *   the matching Member object.
 * - txt format: memberId,pointsAmount,earnedDate,expiryDate.
 * - Does not touch Member.currentPoints/totalPointsEarned - those are
 *   already set directly by members.txt; this only adds ledger "detail"
 *   entries for expiry-reminder reports, without re-summing totals.
 * - ledgerId has prefix SPL, so it won't collide with PL IDs generated by
 *   real point earnings.
 */
public class PointsLedgerDao {

    private static final String FILE_PATH = "data/points_ledger.txt";

    private int ledgerCounter = 0;

    public void loadPointsLedger(ListInterface<Member> memberList) {
        File file = DataFileLocator.locate(PointsLedgerDao.class, FILE_PATH);
        if (file == null) {
            System.out.println("Failed to load " + FILE_PATH + ": file not found near project root");
            return;
        }
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty()) {
                    continue;
                }
                String[] fields = line.split(",");
                String memberId = fields[0].trim();
                int pointsAmount = Integer.parseInt(fields[1].trim());
                String earnedDate = fields[2].trim();
                String expiryDate = fields[3].trim();

                Member member = findMemberById(memberList, memberId);
                if (member == null) {
                    System.out.println("Skipped " + FILE_PATH + " row: no member found for id " + memberId);
                    continue;
                }

                ledgerCounter++;
                String ledgerId = "SPL" + String.format("%06d", ledgerCounter);
                member.addPointsEntry(new PointsLedgerEntry(ledgerId, memberId, pointsAmount, earnedDate, expiryDate));
            }
        } catch (IOException e) {
            System.out.println("Failed to load " + FILE_PATH + ": " + e.getMessage());
        }
    }

    private Member findMemberById(ListInterface<Member> memberList, String memberId) {
        Iterator<Member> iterator = memberList.getIterator();
        while (iterator.hasNext()) {
            Member member = iterator.next();
            if (member.getMemberId().equals(memberId)) {
                return member;
            }
        }
        return null;
    }
}
